openapi: 3.0.0
info:
  title: ""
  version: ""
servers:
- url: /
paths:
  /agent:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAgentRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateAgentResponse"
          description: OK
      x-content-type: application/json
      x-accepts:
      - application/json
  /conversation:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateConversationRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateConversationResponse"
          description: OK
      x-content-type: application/json
      x-accepts:
      - application/json
  /llm_config:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateLLMConfigRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateLLMConfigResponse"
          description: OK
      x-content-type: application/json
      x-accepts:
      - application/json
  /tenant:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTenantRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTenantResponse"
          description: OK
      x-content-type: application/json
      x-accepts:
      - application/json
  /tool:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ToolUpsert"
        required: true
      responses: {}
      x-content-type: application/json
      x-accepts:
      - application/json
  /workflow:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateWorkflowRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateWorkflowResponse"
          description: OK
      x-content-type: application/json
      x-accepts:
      - application/json
  /workflow/{id}:
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetWorkflowResponse"
          description: OK
      x-accepts:
      - application/json
components:
  schemas:
    CreateAgentRequest:
      description: CreateAgent
      example:
        agents:
        - tenant_id: 4
          examples:
          - examples
          - examples
          expected_input: expected_input
          edges:
          - script_condition: script_condition
            target_agent_id: 1
            conditions:
            - 0
            - 0
            priority: 6
          - script_condition: script_condition
            target_agent_id: 1
            conditions:
            - 0
            - 0
            priority: 6
          name: name
          created_at: 2000-01-23T04:56:07.000+00:00
          description: description
          rules:
          - tenant_id: 7
            version_created_at: 2000-01-23T04:56:07.000+00:00
            name: name
            description: description
            id: 5
            position: 2
            version_id: 2
            rule_created_at: 2000-01-23T04:56:07.000+00:00
            tools:
            - name: name
              description: description
              id: 3
              function_declarations:
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
            - name: name
              description: description
              id: 3
              function_declarations:
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
            content: content
            tags:
            - tags
            - tags
          - tenant_id: 7
            version_created_at: 2000-01-23T04:56:07.000+00:00
            name: name
            description: description
            id: 5
            position: 2
            version_id: 2
            rule_created_at: 2000-01-23T04:56:07.000+00:00
            tools:
            - name: name
              description: description
              id: 3
              function_declarations:
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
            - name: name
              description: description
              id: 3
              function_declarations:
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
            content: content
            tags:
            - tags
            - tags
          id: 5
          is_default: 2000-01-23T04:56:07.000+00:00
          tools:
          - name: name
            description: description
            id: 3
            function_declarations:
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
          - name: name
            description: description
            id: 3
            function_declarations:
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
          tags:
          - tags
          - tags
        - tenant_id: 4
          examples:
          - examples
          - examples
          expected_input: expected_input
          edges:
          - script_condition: script_condition
            target_agent_id: 1
            conditions:
            - 0
            - 0
            priority: 6
          - script_condition: script_condition
            target_agent_id: 1
            conditions:
            - 0
            - 0
            priority: 6
          name: name
          created_at: 2000-01-23T04:56:07.000+00:00
          description: description
          rules:
          - tenant_id: 7
            version_created_at: 2000-01-23T04:56:07.000+00:00
            name: name
            description: description
            id: 5
            position: 2
            version_id: 2
            rule_created_at: 2000-01-23T04:56:07.000+00:00
            tools:
            - name: name
              description: description
              id: 3
              function_declarations:
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
            - name: name
              description: description
              id: 3
              function_declarations:
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
            content: content
            tags:
            - tags
            - tags
          - tenant_id: 7
            version_created_at: 2000-01-23T04:56:07.000+00:00
            name: name
            description: description
            id: 5
            position: 2
            version_id: 2
            rule_created_at: 2000-01-23T04:56:07.000+00:00
            tools:
            - name: name
              description: description
              id: 3
              function_declarations:
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
            - name: name
              description: description
              id: 3
              function_declarations:
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
              - internal:
                  provider: provider
                  tags:
                  - tags
                  - tags
                response: "{}"
                name: name
                description: description
                id: 9
                parameters: "{}"
            content: content
            tags:
            - tags
            - tags
          id: 5
          is_default: 2000-01-23T04:56:07.000+00:00
          tools:
          - name: name
            description: description
            id: 3
            function_declarations:
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
          - name: name
            description: description
            id: 3
            function_declarations:
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
          tags:
          - tags
          - tags
      properties:
        agents:
          items:
            $ref: "#/components/schemas/CreateAgentRequest_agents_inner"
          type: array
      required:
      - agents
      type: object
    CreateAgentResponse:
      example:
        id: 0
      properties:
        id:
          format: int64
          type: integer
      required:
      - id
      type: object
    CreateConversationRequest:
      description: CreateConversation
      example:
        tenant_id: 0
      properties:
        tenant_id:
          format: int64
          type: integer
      required:
      - tenant_id
      type: object
    CreateConversationResponse:
      example:
        conversation_id: 0
      properties:
        conversation_id:
          format: int64
          type: integer
      required:
      - conversation_id
      type: object
    CreateTenantRequest:
      description: CreateTenant
      example:
        tenant_id: 6
        determine_conversation_with_narrative: determine_conversation_with_narrative
        determine_conversation_with_agent: 0
        username: username
      properties:
        determine_conversation_with_agent:
          format: int64
          type: integer
        determine_conversation_with_narrative:
          type: string
        tenant_id:
          format: int64
          type: integer
        username:
          type: string
      required:
      - determine_conversation_with_agent
      - determine_conversation_with_narrative
      - tenant_id
      - username
      type: object
    CreateTenantResponse:
      example:
        tenant_id: 0
      properties:
        tenant_id:
          format: int64
          type: integer
      required:
      - tenant_id
      type: object
    CreateWorkflowRequest:
      description: CreateWorkflow
      example:
        cron: cron
        tenant_id: 2
        input: input
        output_event_weight: 3.616076749251911
        agent_id: 0
        input_event_weight: 9.301444243932576
        conversation_id: 6
        freeform: true
        generation_config:
          top_p: 7.061401241503109
          stop_sequences:
          - stop_sequences
          - stop_sequences
          candidate_count: 1
          top_k: 2
          temperature: 5.637376656633329
          max_output_tokens: 5
        cached_content: "{}"
      properties:
        agent_id:
          format: int64
          type: integer
        cached_content:
          type: object
        conversation_id:
          format: int64
          type: integer
        cron:
          type: string
        freeform:
          type: boolean
        generation_config:
          $ref: "#/components/schemas/CreateWorkflowRequest_generation_config"
        input:
          type: string
        input_event_weight:
          format: double
          type: number
        output_event_weight:
          format: double
          type: number
        tenant_id:
          format: int64
          type: integer
      required:
      - freeform
      - input
      - tenant_id
      type: object
    CreateWorkflowResponse:
      example:
        workflow_id: 0
      properties:
        workflow_id:
          format: int64
          type: integer
      required:
      - workflow_id
      type: object
    GetWorkflowResponse:
      description: GetWorkflow
      example:
        events:
        - events
        - events
      properties:
        events:
          items:
            type: string
          type: array
      required:
      - events
      type: object
    ToolUpsert:
      description: Payload for `/tool` PUT
      example:
        tenant_id: 0
        tools:
        - name: name
          description: description
          id: 3
          function_declarations:
          - internal:
              provider: provider
              tags:
              - tags
              - tags
            response: "{}"
            name: name
            description: description
            id: 9
            parameters: "{}"
          - internal:
              provider: provider
              tags:
              - tags
              - tags
            response: "{}"
            name: name
            description: description
            id: 9
            parameters: "{}"
        - name: name
          description: description
          id: 3
          function_declarations:
          - internal:
              provider: provider
              tags:
              - tags
              - tags
            response: "{}"
            name: name
            description: description
            id: 9
            parameters: "{}"
          - internal:
              provider: provider
              tags:
              - tags
              - tags
            response: "{}"
            name: name
            description: description
            id: 9
            parameters: "{}"
      properties:
        tenant_id:
          format: int64
          type: integer
        tools:
          items:
            $ref: "#/components/schemas/CreateAgentRequest_agents_inner_rules_inner_tools_inner"
          type: array
      required:
      - tenant_id
      - tools
      type: object
    UpdateLLMConfigRequest:
      description: UpdateLLMConfig
      example:
        tenant_id: 5
        workflow_id: 5
        api_key: api_key
        project_id: project_id
        provider: provider
        conversation_id: 0
        temperature: 1.4658129805029452
        location: location
        model: model
        id: 6
      properties:
        api_key:
          type: string
        conversation_id:
          format: int64
          type: integer
        id:
          format: int64
          type: integer
        location:
          type: string
        model:
          type: string
        project_id:
          type: string
        provider:
          type: string
        temperature:
          format: double
          type: number
        tenant_id:
          format: int64
          type: integer
        workflow_id:
          format: int64
          type: integer
      required:
      - api_key
      - model
      - provider
      - temperature
      - tenant_id
      type: object
    UpdateLLMConfigResponse:
      example:
        message: message
      properties:
        message:
          type: string
      required:
      - message
      type: object
    CreateAgentRequest_agents_inner_edges_inner:
      example:
        script_condition: script_condition
        target_agent_id: 1
        conditions:
        - 0
        - 0
        priority: 6
      properties:
        conditions:
          description: |-
            0 or more conditions under which the source agent can invoke the associated [target] [Agent]
            If empty, the target can be invoked under any circumstances
          items:
            format: int64
            type: integer
          type: array
        priority:
          description: If two edges could be invoked and both are not required then
            the highest priority one should be executed
          format: int32
          type: integer
        script_condition:
          description: A JavaScript condition which must evaluate to true for the
            agent to be executed
          type: string
        target_agent_id:
          description: "The agent ID that should be called if [script_condition] or\
            \ any of the [conditions] are true"
          format: int64
          type: integer
      required:
      - conditions
      - priority
      - target_agent_id
      type: object
    CreateAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner_internal:
      example:
        provider: provider
        tags:
        - tags
        - tags
      properties:
        provider:
          type: string
        tags:
          items:
            type: string
          type: array
      required:
      - provider
      type: object
    CreateAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner:
      example:
        internal:
          provider: provider
          tags:
          - tags
          - tags
        response: "{}"
        name: name
        description: description
        id: 9
        parameters: "{}"
      properties:
        description:
          type: string
        id:
          format: int64
          type: integer
        internal:
          $ref: "#/components/schemas/CreateAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner_internal"
        name:
          description: "Required. The name of the function to call. Must start with\
            \ a letter or an underscore. Must be a-z, A-Z, 0-9, or contain underscores,\
            \ dots and dashes, with a maximum length of 64."
          type: string
        parameters:
          type: object
        response:
          type: object
      required:
      - description
      - name
      - parameters
      type: object
    CreateAgentRequest_agents_inner_rules_inner_tools_inner:
      example:
        name: name
        description: description
        id: 3
        function_declarations:
        - internal:
            provider: provider
            tags:
            - tags
            - tags
          response: "{}"
          name: name
          description: description
          id: 9
          parameters: "{}"
        - internal:
            provider: provider
            tags:
            - tags
            - tags
          response: "{}"
          name: name
          description: description
          id: 9
          parameters: "{}"
      properties:
        description:
          type: string
        function_declarations:
          items:
            $ref: "#/components/schemas/CreateAgentRequest_agents_inner_rules_inner_tools_inner_function_declarations_inner"
          type: array
        id:
          format: int64
          type: integer
        name:
          type: string
      required:
      - function_declarations
      type: object
    CreateAgentRequest_agents_inner_rules_inner:
      example:
        tenant_id: 7
        version_created_at: 2000-01-23T04:56:07.000+00:00
        name: name
        description: description
        id: 5
        position: 2
        version_id: 2
        rule_created_at: 2000-01-23T04:56:07.000+00:00
        tools:
        - name: name
          description: description
          id: 3
          function_declarations:
          - internal:
              provider: provider
              tags:
              - tags
              - tags
            response: "{}"
            name: name
            description: description
            id: 9
            parameters: "{}"
          - internal:
              provider: provider
              tags:
              - tags
              - tags
            response: "{}"
            name: name
            description: description
            id: 9
            parameters: "{}"
        - name: name
          description: description
          id: 3
          function_declarations:
          - internal:
              provider: provider
              tags:
              - tags
              - tags
            response: "{}"
            name: name
            description: description
            id: 9
            parameters: "{}"
          - internal:
              provider: provider
              tags:
              - tags
              - tags
            response: "{}"
            name: name
            description: description
            id: 9
            parameters: "{}"
        content: content
        tags:
        - tags
        - tags
      properties:
        content:
          type: string
        description:
          type: string
        id:
          format: int64
          type: integer
        name:
          type: string
        position:
          format: int64
          type: integer
        rule_created_at:
          format: date-time
          type: string
        tags:
          items:
            type: string
          type: array
        tenant_id:
          format: int64
          type: integer
        tools:
          items:
            $ref: "#/components/schemas/CreateAgentRequest_agents_inner_rules_inner_tools_inner"
          type: array
        version_created_at:
          format: date-time
          type: string
        version_id:
          format: int64
          type: integer
      required:
      - content
      - description
      - id
      - name
      - position
      - rule_created_at
      - tenant_id
      - version_created_at
      - version_id
      type: object
    CreateAgentRequest_agents_inner:
      example:
        tenant_id: 4
        examples:
        - examples
        - examples
        expected_input: expected_input
        edges:
        - script_condition: script_condition
          target_agent_id: 1
          conditions:
          - 0
          - 0
          priority: 6
        - script_condition: script_condition
          target_agent_id: 1
          conditions:
          - 0
          - 0
          priority: 6
        name: name
        created_at: 2000-01-23T04:56:07.000+00:00
        description: description
        rules:
        - tenant_id: 7
          version_created_at: 2000-01-23T04:56:07.000+00:00
          name: name
          description: description
          id: 5
          position: 2
          version_id: 2
          rule_created_at: 2000-01-23T04:56:07.000+00:00
          tools:
          - name: name
            description: description
            id: 3
            function_declarations:
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
          - name: name
            description: description
            id: 3
            function_declarations:
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
          content: content
          tags:
          - tags
          - tags
        - tenant_id: 7
          version_created_at: 2000-01-23T04:56:07.000+00:00
          name: name
          description: description
          id: 5
          position: 2
          version_id: 2
          rule_created_at: 2000-01-23T04:56:07.000+00:00
          tools:
          - name: name
            description: description
            id: 3
            function_declarations:
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
          - name: name
            description: description
            id: 3
            function_declarations:
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
            - internal:
                provider: provider
                tags:
                - tags
                - tags
              response: "{}"
              name: name
              description: description
              id: 9
              parameters: "{}"
          content: content
          tags:
          - tags
          - tags
        id: 5
        is_default: 2000-01-23T04:56:07.000+00:00
        tools:
        - name: name
          description: description
          id: 3
          function_declarations:
          - internal:
              provider: provider
              tags:
              - tags
              - tags
            response: "{}"
            name: name
            description: description
            id: 9
            parameters: "{}"
          - internal:
              provider: provider
              tags:
              - tags
              - tags
            response: "{}"
            name: name
            description: description
            id: 9
            parameters: "{}"
        - name: name
          description: description
          id: 3
          function_declarations:
          - internal:
              provider: provider
              tags:
              - tags
              - tags
            response: "{}"
            name: name
            description: description
            id: 9
            parameters: "{}"
          - internal:
              provider: provider
              tags:
              - tags
              - tags
            response: "{}"
            name: name
            description: description
            id: 9
            parameters: "{}"
        tags:
        - tags
        - tags
      properties:
        created_at:
          format: date-time
          type: string
        description:
          type: string
        edges:
          items:
            $ref: "#/components/schemas/CreateAgentRequest_agents_inner_edges_inner"
          type: array
        examples:
          items:
            type: string
          type: array
        expected_input:
          description: The info the agent expects in its prompt
          type: string
        id:
          format: int64
          type: integer
        is_default:
          format: date-time
          type: string
        name:
          type: string
        rules:
          items:
            $ref: "#/components/schemas/CreateAgentRequest_agents_inner_rules_inner"
          type: array
        tags:
          items:
            type: string
          type: array
        tenant_id:
          format: int64
          type: integer
        tools:
          items:
            $ref: "#/components/schemas/CreateAgentRequest_agents_inner_rules_inner_tools_inner"
          type: array
      required:
      - created_at
      - description
      - edges
      - expected_input
      - id
      - name
      - rules
      - tenant_id
      - tools
      type: object
    CreateWorkflowRequest_generation_config:
      example:
        top_p: 7.061401241503109
        stop_sequences:
        - stop_sequences
        - stop_sequences
        candidate_count: 1
        top_k: 2
        temperature: 5.637376656633329
        max_output_tokens: 5
      properties:
        candidate_count:
          format: int32
          type: integer
        max_output_tokens:
          format: int32
          type: integer
        stop_sequences:
          items:
            type: string
          type: array
        temperature:
          format: double
          type: number
        top_k:
          format: int32
          type: integer
        top_p:
          format: double
          type: number
      type: object

